# Generated by Django 3.0.3 on 2020-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200222_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='picture'),
        ),
    ]
